### ISSUE TITLE
Add BungeeCord support

### ISSUE THREAD

**Issue by bittiez** [bittiez/ResponseBot#7]
Add support for BungeeCord - Will be a seperate plugin

**Comment by donleo123** [comment]
Its not an issue?

**Comment by bittiez** [comment]
That's why it's labeled as an enhancement

**Comment by bittiez** [comment]
Unfortunately due to the amount of work required to make this work, I am not going to officially support BungeeCord, sorry guys! You can, however, install a copy of ResponseBot on each of your servers, this will actually give you more flexibility because you could have certain responses that relate only to one of your servers.
Again, sorry!
