### ISSUE TITLE
Add debug option for logging

### ISSUE THREAD

**Issue by mb243** [bittiez/ResponseBot#9]
With `replyToPlayer: true`, there's no way to log the responses the bot is sending to the players or how accurate it is. 

Could you please add a debugging configuration option that would log detected player inputs and the bot's responses, either to the main server log (preferable) or a separate log file?

**Comment by mb243** [comment]
Just to clarify, this would ideally only log matched/replied to phrases and not _every_ phrase. The purpose of this would be to log what the bot is saying to people in response to their queries.

**Comment by bittiez** [comment]
I do plan to implement this, as some would find it useful, however just note that API.ai has a Training tab that saves all messages and allows you to approve/disapprove them to train your bot better

**Comment by bittiez** [comment]
Added with 459c17ca6fb338e432b8d8016369f90a5b3ffd6f
